language: python
python:
  - 2.7
  - 2.6
install:
  - pip install nose
  - pip install unittest2
  - python setup.py develop
script:
  - nosetests envisage/tests

notifications:
  email:
    - pberkes@enthought.com
