language: python
python:
  - 2.7
  - 2.6
virtualenv:
  system_site_packages: true
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sudo apt-get install python-qt4 python-qt4-dev
  - python -c 'import PyQt4'
  - python -c 'import PyQt4.QtCore'
  - python -c 'import PyQt4.QtGui'
  - "export ETS_TOOLKIT=qt4"
install:
  - pip install nose
  - pip install unittest2
  - python setup.py develop
script:
  - nosetests envisage
notifications:
  email:
    - pberkes@enthought.com
